#!/bin/bash


while read local_ref local_sha remote_ref remote_sha
do
    # Check if we are pushing tags
    if [[ $local_ref == refs/tags/* ]]; then
        # Extract the tag name
        tag_name=${local_ref#refs/tags/}
        make check_release_version VERSION=${tag_name}
    fi
done
